[package]
name = "git-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.18"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.4"
tokei = "12.1"
colored = "=3.0.0"
